blank_lines_lower_bound = 0
blank_lines_upper_bound = 3
comment_width = 110
edition = "2018"
fn_args_layout = "Vertical"
force_multiline_blocks = true
format_code_in_doc_comments = true
imports_layout = "Vertical"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
spaces_around_ranges = false
struct_field_align_threshold = 20
trailing_comma = "Vertical"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
max_width = 120
merge_imports = true